#!/usr/bin/env sh

version=1.010

echo "\n* Downloading version $version of source code pro font"
wget https://github.com/downloads/adobe/source-code-pro/SourceCodePro_FontsOnly-$version.zip -o /tmp/SourceCodePro_FontsOnly-$version.zip

echo "\n* Unziping package"
(cd /tmp; unzip SourceCodePro_FontsOnly-$version.zip)
mkdir -p ~/.fonts

echo "\n* Copying fonts to ~/fonts"
cp /tmp/SourceCodePro_FontsOnly-$version/OTF/*.otf ~/.fonts/

echo "\n* Updating font cache"
sudo fc-cache -f -v

echo "\n* Looking for 'Source Code Pro' in installed fonts"
fc-list | grep "Source Code Pro"

echo "\n* You may need to restart apps before it shows up."
